-- Tabel Users
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_datetime TIMESTAMP(6),
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    phone VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    updated_datetime TIMESTAMP(6)
);

INSERT INTO public.users (id, created_by, created_datetime, email, first_name, last_name, phone, updated_by, updated_datetime)
VALUES 
    (1, NULL, '2025-03-12 16:19:01.242', 'zikri.rahman@gmail.com', 'Zikri', 'Rahman', '081122334455', NULL, '2025-03-12 16:19:01.243');


-- Tabel Items
CREATE TABLE items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost INTEGER NOT NULL,
    created_by VARCHAR(255),
    created_datetime TIMESTAMP(6),
    description VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    updated_by VARCHAR(255),
    updated_datetime TIMESTAMP(6)
);

INSERT INTO public.items (id, cost, created_by, created_datetime, description, name, price, updated_by, updated_datetime)
VALUES 
    (1, 8000, NULL, '2025-03-12 16:19:11.307', 'Gaming Laptop', 'Laptop', 12000, NULL, '2025-03-12 16:19:11.307');


-- Tabel PO_H
CREATE TABLE po_h (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_datetime TIMESTAMP(6),
    datetime TIMESTAMP(6),
    description VARCHAR(255),
    total_cost INTEGER NOT NULL,
    total_price INTEGER NOT NULL,
    updated_by VARCHAR(255),
    updated_datetime TIMESTAMP(6)
);

INSERT INTO public.po_h (id, created_by, created_datetime, datetime, description, total_cost, total_price, updated_by, updated_datetime)
VALUES 
    (1, NULL, '2025-03-12 16:19:22.983', '2025-03-12 16:19:22.984', 'Test Order', 120000, 180000, NULL, '2025-03-12 16:19:23.536');


-- Tabel PO_D
CREATE TABLE po_d (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_cost INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    item_price INTEGER NOT NULL,
    item_qty INTEGER NOT NULL,
    poh_id INTEGER NOT NULL REFERENCES po_h(id)
);

INSERT INTO public.po_d (id, item_cost, item_id, item_price, item_qty, poh_id)
VALUES 
    (1, 8000, 1, 12000, 10, 1),
    (2, 8000, 2, 12000, 5, 1);


-- Query Select
SELECT * FROM users;
SELECT * FROM items;
SELECT * FROM po_h;
SELECT * FROM po_d;
